.gitattributes
configure.ac

* Better git diff/show output for python scripts.
* Change git code version to 1.2 as development version. Or even 1.1.99?

Two trivial changes about git setting and versioning.

---

doc/lsmcli.bash

* Change default behavior to not do value look ups, override with LSMCLI_AUTO_COMPLETE_VALUE=1
* Added filtering of initiators when an --ag is present on the command line
* Added aliases

Bash completion support

---

daemon/lsm_daemon.c
daemon/lsm_rest.c
plugin/simc/simc_lsmplugin.c

* Updated the code formatting for lsm_daemon.c, lsm_rest.c and simc_lsmplugin.c
* Restructured the code in lsm_daemon.c to remove a coverity warning.

Code reformatting & coverity fix

---

c_binding/include/libstoragemgmt/libstoragemgmt.h
c_binding/lsm_convert.hpp
python_binding/lsm/_client.py

Corrections and updates for the latest code.

doxygen fixes

---

test/runtests.sh

Problem:
"make check" will fail when run it as root with libstoragemgmt user
account exists.
Root cause:
lsmd found libstoragemgmt user and drop privilege to that user.
But the plugin codes are in /root folder where libstoragemgmt user
has no access, which then lead to failure.
Fix:
Copy python modules to /tmp/<random>/python folder as we did to
C lib file.

Fix "make check" when running as root.

---

plugin/hpsa/hpsa.py

HPSSACLI output is improperly indented when an Array contains Mirror Group entries. This workaround modifies the Mirror Group sub-items in the HPSSACLI parsing method to be properly indented. Without this workaround, physical drives (Disks) are improperly parsed. See snippet of failing HPSSACLI output below. The lines marked "<== This line should be indented" below are treated as headers a level above the Mirror Group entries rather than items belonging to the Mirror Group.
Array: A
Interface Type: SATA
Unused Space: 0  MB (0.0%)
Used Space: 1.8 TB (100.0%)
Status: OK
Array Type: Data
HP SSD Smart Path: disable
Logical Drive: 1
Size: 931.5 GB
Fault Tolerance: 1
Heads: 255
Sectors Per Track: 32
Cylinders: 65535
Strip Size: 256 KB
Full Stripe Size: 256 KB
Status: OK
Caching:  Disabled …

HP SmartArray Plugin: Workaround for bad HPSSACLI Array Mirror Group output

---

c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
c_binding/include/libstoragemgmt/libstoragemgmt_systems.h
c_binding/include/libstoragemgmt/libstoragemgmt_types.h
c_binding/lsm_convert.cpp
c_binding/lsm_datatypes.cpp
c_binding/lsm_datatypes.hpp
plugin/hpsa/hpsa.py
plugin/megaraid/megaraid.py
plugin/sim/simarray.py
plugin/simc/simc_lsmplugin.c
python_binding/lsm/_data.py
test/plugin_test.py
test/tester.c
tools/lsmcli/data_display.py

Adding new system property: `lsm.System.mode` and `lsm_system_mode_get()`.
Please check patch for detail.
TODO: Need HP's help on hpsa plugin, the original HP patch #52 does not works
works on my system.

[PATCH V2 0/8] Adding new system property: system mode.

---

python_binding/lsm/_common.py
python_binding/lsm/_data.py

Signed-off-by: Ma Shimiao <shimiao.ma@gmail.com>

specify parameter name for default_property

---

test/Makefile.am
tools/lsmenv

* Fix 'make dist' error.
* Fix using lsmenv along with installed lsmd.

Misc fixes

---

test/test_include.sh
tools/utility/check_const.pl

* Fix error when run 'make check' as root user. Issue #93 
* Fix constants check.

Fix 'sudo make check'

---

c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
c_binding/include/libstoragemgmt/libstoragemgmt_disk.h
c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
c_binding/lsm_convert.cpp
c_binding/lsm_datatypes.cpp
c_binding/lsm_datatypes.hpp
plugin/hpsa/hpsa.py
plugin/sim/simarray.py
plugin/simc/simc_lsmplugin.c
python_binding/lsm/_data.py
test/plugin_test.py
test/tester.c

libstoragemgmt: Pull path information for physical disks

---

c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
c_binding/include/libstoragemgmt/libstoragemgmt_systems.h
c_binding/include/libstoragemgmt/libstoragemgmt_types.h
c_binding/lsm_convert.cpp
c_binding/lsm_datatypes.cpp
c_binding/lsm_datatypes.hpp
plugin/hpsa/hpsa.py
plugin/sim/simarray.py
plugin/simc/simc_lsmplugin.c
python_binding/lsm/_data.py
test/plugin_test.py
test/tester.c
tools/lsmcli/data_display.py

libstoragemgmt: Add read_cache_pct system property

---

test/plugin_test.py

Test: Update sys mode python test to check the correct values.

---

test/plugin_test.py

This should help keep the hardware from getting filled up.

plugin_test.py: Clean-up what we create in tearDown

---

plugin/hpsa/hpsa.py

*  HPSA Plugin: Fix disk querying in RAID mode.
*  HPSA plugin: Fix RAID volume creating.

[PATCH 0/2] Fixes for HP SmartArray plugin.

---

.travis.yml
configure.ac
packaging/libstoragemgmt.spec.in
plugin/hpsa/hpsa.py
plugin/hpsa/utils.py

Signed-off-by: mulhern <amulhern@redhat.com>

Use pyudev to obtain sysfs attributes.

---

plugin/hpsa/hpsa.py

HPE Smart Array: Add basic delete support for Smart Arrays

---

c_binding/include/libstoragemgmt/libstoragemgmt.h
c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
c_binding/lsm_mgmt.cpp
c_binding/lsm_plugin_ipc.cpp
doc/man/lsmcli.1.in
plugin/hpsa/hpsa.py
plugin/sim/simarray.py
plugin/sim/simulator.py
plugin/simc/simc_lsmplugin.c
python_binding/lsm/_client.py
test/cmdtest.py
test/plugin_test.py
test/tester.c
tools/lsmcli/cmdline.py

volume-led-on/off: Update volume-led APIs to on/off naming

---

tools/bash_completion/lsmcli

bash completion: Updated for post-1.2 additions to lsmcli

---

plugin/sim/simarray.py
tools/lsmcli/data_display.py

Fixes for lsmcli disk_location and simarray disk_location values

---

plugin/hpsa/hpsa.py

HPE Smart Array: Return STATUS_OK when a cache module reports as unconfigured

---

test/webtest/test_automated.py

We are leaving processes hanging around for plugin tests that are not completing in time.

test_automated.py: Send SIGKILL instead of SIGTERM

---

c_binding/utils.c
plugin/hpsa/hpsa.py
plugin/ontap/ontap.py
plugin/smispy/smis.py
test/plugin_test.py
tools/lsmcli/cmdline.py

A number of misc. issues found with a coverity scan.

Coverity fixes

---

plugin/megaraid/megaraid.py

* With some MegaRAID/PERC(for example PERC H700), disks have no
enclosure ID[1] which use '/cx/sall show all J' for disk querying.
This patch try both '/c0/eall/sall show all J' and
'/c0/sall show all J' for disk querying.
* Also fixed the volume_raid_create() to support empty enclosure ID disks.
* Tested on both enclosure disk and non-enclosure disk.
[1]: Please be informed, the enclosure here does not mean physical
enclosure, I(Gris) have a MegaRAID card with 4 SATA disks directly
attached to it, they all still have enclosure ID.
I am guessing some old firmware or old MegaRAID/PERC card does not
support enclosure ID. Anyway, we support both ways.

MegaRAID plugin: Support disks with no enclosure.

---

plugin/ontap/na.py
plugin/ontap/ontap.py

See: https://bugzilla.redhat.com/show_bug.cgi?id=1346901
More information:
https://kb.netapp.com/support/index?page=content&id=3012229

ontap plugin: Correct error code for large re-size

---

c_binding/lsm_local_disk.c

Problem:
In libvirt VM(qemu VM), 'lsmcli ld -u sim://' got segfault.
Root cause:
The /dev/sda provided by qemu VM does not have SCSI VPD83 NAA ID in
sysfs or udev, which cause lsm_local_disk_vpd83_get() return NULL
vpd83 with LSM_ERR_OK. Then strncmp() in lsm_local_disk_vpd83_search()
triggered segfault on comparing NULL pointer.
Fix:
1. Return LSM_ERR_NO_SUPPORT when udev has no ID_WWN_WITH_EXTENSION
property.
2. Make sure string is not NULL before invoking strncmp() and return
LSM_ERR_LIB_BUG if got NULL vpd83 with LSM_ERR_OK.

Bug fix: lsm_local_disk_vpd83_search() got segfault on qemu simulated disk

---

tools/lsmcli/cmdline.py

@cathay4t Please take a look at this to see what you think.  I wasn't able to twiddle the argparse library to get things to work correctly, but maybe you will have better luck.  Maybe I'm missing something obvious, but this change is very straight forward and appears to restore things to a working state.  Address issue #97 
I fear we have out grown argparse with some of the things we are trying to do.  I know the py3 conversion has some ugly behavior with our use and abuse of argparse.

cmdline.py: Alternative way to handle aliases

---

plugin/hpsa/hpsa.py

plugins/hpsa: Add DISK_VPD83_GET capability

---

plugin/hpsa/hpsa.py

plugin/hpsa: Update possible binary locations for SSA tools

---

daemon/lsm_daemon.c
doc/man/lsmd.1.in

Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

doc/man: add --confdir for lsmd

---

plugin/hpsa/hpsa.py

Fix hpsa raid mode

---

deb_dependency

dep_dependency: Add sqlite package

---

python_binding/lsm/_local_disk.py

_local_disk.py: Fixup class in link_type_get usage

---

python_binding/lsm/_data.py

data.py: Add Joe to authors

---

python_binding/lsm/_data.py

Signed-off-by: Joe Handzik <joseph.t.handzik@hpe.com>
Missed the copyright when I added myself to authors here. Also, I needed to retry the HPE CI integration again. :)

data.py: Add HPE copyright

---

c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
c_binding/libsg.c
c_binding/libsg.h
c_binding/lsm_local_disk.c
c_binding/utils.c
c_binding/utils.h
configure.ac
python_binding/lsm/_clib.c
python_binding/lsm/_local_disk.py
test/tester.c
tools/lsmcli/cmdline.py
tools/lsmcli/data_display.py

Fixes issue #203
Signed-off-by: Joe Handzik joseph.t.handzik@hpe.com

local_disk: Extract serial number from vpd80

---

python_binding/lsm/_clib.c

Signed-off-by: Joe Handzik <joseph.t.handzik@hpe.com>

_clib.c: Fix minor function header alignment issue

---

c_binding/libsg.c
tools/lsmcli/cmdline.py

~~~Don't commit yet. Will rebase after #207.~~~
* Fix `lsmcli ldl` try-except workflow.
* Fix local disk rpm get failure on NVMe disks.

Bug fixes for local disk rpm get on NVMe.

---

plugin/nstor/nstor.py
test/plugin_test.py.in

Ref: https://github.com/libstorage/libstoragemgmt/issues/234

Try and make plugin_test.py concurrent friendly

---

c_binding/lsm_local_disk.c
c_binding/utils.c
c_binding/utils.h
configure.ac
m4/ax_check_compile_flag.m4
plugin/simc/db.c
plugin/simc/fs_ops.c
plugin/simc/mgm_ops.c
plugin/simc/nfs_ops.c
plugin/simc/ops_v1_2.c
plugin/simc/ops_v1_3.c
plugin/simc/san_ops.c
plugin/simc/simc_lsmplugin.c
plugin/simc/utils.h
python_binding/lsm/_clib.c
test/tester.c
tools/udev/scan-scsi-target.c

* Enable GCC `-Wall`, `-Werror` and `-Wextra` flags.
Note: Testing CI

Enable GCC warnings and fix found warnings.

---

NEWS
configure.ac
packaging/libstoragemgmt.spec.in

@tasleson @joehandzik Any thing you want to add before tag 1.4.0?

New release 1.4.0

---

test/trusted.yaml

trusted.yaml: Add cvedel

---

plugin/hpsa/hpsa.py

move list call to the right level, fixes #251

---

plugin/hpsa/hpsa.py

Another one caught by @cvedel through his testing. I'll mitigate this problem in the future by adding a second HPE machine to the lsm CI infrastructure, this time in RAID mode.

HPSA plugin: Clean up py3 problems from RAID mode

---

plugin/hpsa/hpsa.py

HPSA: Work around Smart HBA name mismatch

---

c_binding/libsg.c
test/cmdtest.py.in

Addresses https://github.com/libstorage/libstoragemgmt/issues/166
Found  a couple of bugs putting this in place.

Lsmcli daemon missing test

---

test/cmdtest.py.in

Misc cmdtest fixes

---

config/pluginconf.d/arcconf.conf
configure.ac
doc/man/Makefile.am
doc/man/arcconf_lsmplugin.1.in
plugin/Makefile.am
plugin/arcconf/Makefile.am
plugin/arcconf/__init__.py
plugin/arcconf/arcconf.py
plugin/arcconf/arcconf_lsmplugin.in
plugin/arcconf/utils.py

Added the raid volume create support for arcconf.

New plugin for Adaptec RAID

---

AUTHORS
plugin/arcconf/arcconf.py

* Just fix some indentation and unused variable issues.

arcconf plugin: Fix pylint warnings.

---

config/Makefile.am
config/pluginconf.d/nfs.conf
configure.ac
doc/man/Makefile.am
doc/man/nfs_lsmplugin.1.in
packaging/libstoragemgmt.spec.in
plugin/Makefile.am
plugin/nfs/Makefile.am
plugin/nfs/nfs.py
plugin/nfs/nfs_clib.c
plugin/nfs/nfs_lsmplugin.in
test/test_include.sh

Same functionality as before but now mostly written in python, certain tasks seemed difficult to do directly from python so have been written in C, they are not specific to NFS and may be useful to other plugins later so have gone into the local_disk code.

Local filesystem NFS plugin reworked in python

---

config/Makefile.am
packaging/libstoragemgmt.spec.in
test/runtests.sh.in
test/test_include.sh

* Only keep the Fedora version rpm spec.
* Add new sub-package for arcconf plugin.

RPM SPEC clean up

---

plugin/nfs/nfs.py

* Change system id and name to include NFS in it.

NFS plugin: Change system id and name.

---

plugin/megaraid/megaraid.py

* Support `Pool.STATUS_RECONSTRUCTING` and `Pool.STATUS_VERIFYING`. Tested on MegaRAID 9286CV-8eCC
* Fix when both `perccli` and `storcli` are installed. Tested on Dell PERC and Broadcom MegaRAID

Improve pool status of MegaRAID plugin

---

test/webtest/test_results.py

Remove source code hyperlink

---

packaging/libstoragemgmt.spec.in

Ontap: Remove m2crypto requirement

---

c_binding/libata.c
c_binding/libata.h
c_binding/libsg.c
c_binding/libsg.h
c_binding/lsm_local_disk.c
c_binding/utils.h

Fix issue found in https://gist.github.com/cathay4t/96335dddbf4399755b091cda69fffb02

Clean up code covscan warnings.

---

configure.ac
tools/sanity_check/local_sanity_check.py.in

* Use libstoragemgmt API to check status and configuration of local
disk matched by Volume vpd83.
* Check volume cache setting for write back cache and physical disk
cache.
* Check pool and system status.

New tool for sanity check on local disks.

---

INSTALL
configure.ac
deb_dependency
packaging/libstoragemgmt.spec.in
plugin/hpsa/hpsa.py
rh_rpm_dependency
suse_rpm_dependency
test/docker_travis_test.sh

Removed the pyudev codes from hpsa plugin.
https://github.com/libstorage/libstoragemgmt/issues/194

SmartArray plugin: Remove the pyudev codes.

---

.travis.yml
c_binding/libsg.c
c_binding/utils.h
daemon/lsm_daemon.c
plugin/simc/db.c
plugin/simc/nfs_ops.c
plugin/simc/san_ops.c
plugin/simc/utils.h
python_binding/Makefile.am
test/docker_travis_test.sh

Tested on Fedora rawhide `gcc-8.0.1-0.19.fc29.x86_64`

Fix compile warnnings on gcc 8

---

.travis.yml
Makefile.am
configure.ac
debian/libstoragemgmt-tools.install
packaging/libstoragemgmt.spec.in
test/docker_travis_test.sh
tools/Makefile.am

Just some trivial fixes:
* RPM SPEC: Sync with Fedora rawhide
* Fix `make distcheck` on hardcoded systemd tmpfile.d
* Install user case tools to /usr/bin/lsm.d folder.
* Enable debian and Ubuntu CI testing.

Tagging 1.6.2.

---

plugin/hpsa/hpsa.py

hpsa: Handle 'Warning:' in output

---

configure.ac
doc/man/Makefile.am
plugin/Makefile.am
plugin/nfs/Makefile.am
plugin/nstor/Makefile.am
plugin/ontap/Makefile.am
plugin/sim/Makefile.am
plugin/simc/Makefile.am
plugin/smispy/Makefile.am
plugin/targetd/Makefile.am

Add `configure` options to build without any of the plugins.

All optional

---

c_binding/include/libstoragemgmt/libstoragemgmt_disk.h
c_binding/include/libstoragemgmt/libstoragemgmt_fs.h
c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
configure.ac
doc/Makefile.am
doc/man/lsmcli.1.in
packaging/libstoragemgmt.spec.in
tools/Makefile.am

Some things found from the last build & package release
CI Kick number 1

Correct build warnings & errors

---

configure.ac
tools/use_cases/find_unused_lun.py.in

Set specific interpreter for find_unused_lun.py

---

.gitignore
.travis.yml
NEWS
configure.ac
deb_dependency
doc/man/lsmcli.1.in
plugin/sim/simarray.py
plugin/sim/simulator.py
python_binding/lsm/_common.py
tools/lsmcli/cmdline.py

Corrections for a number of bugs that have been sitting around, more corrections to come.

Misc. fixes

---

NEWS
configure.ac

Prepare for new release

---

test/integration.sh

Add simple integration test

---

test/trusted.yaml

Add Harry Mallon to trusted repos

---

plugin/arcconf/arcconf.py
test/plugin_test.py.in

This PR is the collection of all of the outstanding PR's from @sharath-t and a few minor changes that I added at the end.  I squashed the commits that were titled `code refactoring ...` with the appropriate partnered commit.
@sharath-t @cathay4t If you both could take a look and see if everything looks good I would like to get this merged soon as I would like to create a new release.

Arcconf additions and corrections

---

AUTHORS

Add addl. authors

---

plugin/arcconf/arcconf.py

This PR is for the issue https://github.com/libstorage/libstoragemgmt/issues/374
This PR has changes in 3 public functions - 'systems()', 'pools()' and 'volumes()' and 2 private functions '_arcconf_array_to_lsm_pool()' and '_arcconf_ld_to_lsm_vol()'
* since 'System ID' is displayed in list type of 'volumes' and 'pools', changes are made in those functions to have controller serial number as sys_id
* since 'arcconf getconfigJSON' is dependent on the controller number, additional variable 'arcconf_ctrl_num' is introduced to have controller number in 'pools()' and 'volumes()'
* APIs dependent on pools and volumes need to read controller numbers as well. hence the 'plugin_data' variable in pools and volumes will have 'ctrl_num' instead of 'sys_id'
CI Redo

Change System.id of arcconf to use Controller Serial Number

---

NEWS
configure.ac

Prepare new release

---

plugin/sim/simarray.py

Correctly handle simulator FS & Volume re-size to meet expectations.
ref. Correction for https://bugzilla.redhat.com/show_bug.cgi?id=1585169

Sim fs resize

---

.travis.yml

Disabling until we figure out what's broken.
CI kick

Disable debian:testing

---

tools/udev/scan-scsi-target.c

Fixed location of fcntlh.h include

---

c_binding/util/qparams.h

Added work around to always make __GNUC_PREREQ available

---

c_binding/json.hpp

Update nlohmann JSON

---

AUTHORS

AUTHORS: Update

---

.travis.yml
configure.ac
deb_dependency
debian/rules
rh_py2_rpm_dependency
test/docker_travis_test.sh

These were missing when building on RHEL6.

Misc. corrections for different distributions

---

.travis.yml
test/docker_travis_test.sh

Docker script update

---

configure.ac

configure.ac: Workaround for travis 18.04 ubuntu build

---

NEWS
configure.ac

New release prep.

---

plugin/hpsa/hpsa.py

Signed-off-by: STOYANOV Christophe <christophe.stoyanov@scality.com>
CI restart.

419: support new encryption information in the ssacli report for hpsa plugin

---

test/tester.c

Fix i386 compile build failure

---

plugin/hpsa/hpsa.py

When the RAID adapter has a 'Cache Status' of
'Permanently Disabled', disable the capability
SYS_READ_CACHE_PCT_UPDATE.

hpsa: Account for cache perm. disabled

---

plugin/hpsa/hpsa.py

Resolves: https://github.com/libstorage/libstoragemgmt/issues/420
Note: This change is an adaptation of the one provided by
Christophe Stoyanov.  Specifically, when we cannot retrieve all
the needed values we select default values of the proper type
and domain eg.
id, disk_name -> string
blk_size, blk_count -> unsigned integer
rpm -> Disk.RPM_UNKNOWN

Smart array: Handle errored disk

---

AUTHORS

Add Christophe Stoyanov

---

c_binding/libses.c
c_binding/lsm_value_jsmn.hpp
daemon/lsm_daemon.c
plugin/simc/ops_v1_2.c
test/test_include.sh
test/tester.c

A number of misc. fixes for a number of different things.

Static check fixes

---

NEWS
configure.ac

Bump version

---

tools/utility/check_const.pl

Remove problematic language

---

rh_py2_rpm_dependency
rh_py3_rpm_dependency

Add kernel-headers deps.

---

c_binding/libnvme.c
c_binding/libses.c
c_binding/lsm_datatypes.cpp
daemon/lsm_daemon.c
python_binding/lsm/_client.py
tools/udev/scan-scsi-target.c

resolves https://github.com/libstorage/libstoragemgmt/issues/398

Address issues with static code analysis & a reported issue

---

NEWS
configure.ac

New release

---

test/docker_ci_test.sh
test/runtests.sh.in

Prevent changes in base library from breaking golang module, or
at least make them known so they can be fixed.
CI: Kick

CI: Test libStorageMgmt golang module

---

test/runtests.sh.in

Add CI test for rust

---

c_binding/libnvme.c

* Typo correction
* Check for invalid log page, return no support instead of library error

NVMe fixes

---

plugin/megaraid_plugin/megaraid.py
python_binding/lsm/_common.py

* Handle new binary path
* Handle different exit values between versions
* Correct integer division for RAID10

Megaraid fixes

---

test/plugin_test.py.in

Add raid info test

---

test/runtests.sh.in
test/test_include.sh

* Check for golang and rust directories before fetching
* `shellcheck` warnings corrections

Improve tests

---

.clang-format
c_binding/libata.c
c_binding/libsas.c
c_binding/libses.c
c_binding/libses.h
c_binding/libsg.c
c_binding/libsg.h
c_binding/lsm_local_disk.c
c_binding/lsm_value_jsmn.hpp
daemon/lsm_daemon.c
plugin/simc/db.c
plugin/simc/ops_v1_2.c
test/tester.c

A version which supports AlignConsecutiveBitFields is available.

Reformat C code

---

test/cmdtest.py.in
tools/lsmcli/cmdline.py

Correcting and test for `argparse` behavior change.

Fix cmd and test

---

c_binding/lsm_value_jsmn.hpp

Remove some public symbols that shouldn't be public

Fix visibility

---

configure.ac
plugin/hpsa_plugin/hpsa.py
plugin/megaraid_plugin/megaraid.py
tools/utility/check_const.pl

Mainly checking to see if pre-released pywbem package works with targetd plugin in our CI.

Correct misc. typos

---

packaging/daemon/libstoragemgmt.conf

This addresses part of the issue: https://github.com/libstorage/libstoragemgmt/issues/514
resloves: https://github.com/libstorage/libstoragemgmt/issues/514

Update run directory

---

.packit.yaml

Adding support for packit.dev

---

.packit.yaml

Need to handle spec file changes to build el7.

Packit: remove el7 build

---

.circleci/config.yml
NEWS
c_binding/libsg.c
c_binding/lsm_datatypes.cpp
c_binding/lsm_ipc.cpp
c_binding/lsm_local_disk.cpp
c_binding/lsm_mgmt.cpp
c_binding/lsm_value_jsmn.hpp
c_binding/uri_parser.hpp
c_binding/utils.c
configure.ac
daemon/lsm_daemon.c
packaging/libstoragemgmt.spec.in
plugin/nfs_plugin/nfs.py
plugin/simc/db.c
plugin/simc/utils.c
python_binding/lsm/_clib.c
test/tester.c
tools/udev/scan-scsi-target.c

* Bump version
* Update NEWS
* Corrections for static code analysis
CI kick

Prep new release

---

NEWS
configure.ac

Prep. for new release
