- plugin/megaraid/megaraid.py
* Bug fixes patches:
* MegaRAID Plugin: Add missing capability VOLUME_RAID_INFO
* MegaRAID Plugin: Fix incorrect system status query.
* Code tidy up patches:
* MegaRAID Plugin: Use Client.FLAG_RSVD instead of flags=0.
* MegaRAID Plugin: Fix incorrect internal constant name:
_DEFAULT_MDADM_BIN_PATHS
* MegaRAID Plugin: Remove unused import of strip.
* MegaRAID Plugin: Fix Anomalous backslash in string of regex.
Changes in V2:
* Patch 4/7: Use _DEFAULT_BIN_PATHS instead.
* Patch 7/7: New patch: Remove duplicate import  'search_property'.
> [PATCH V2 0/7] MegaRAID Plugin bug fixes and code tidy up.

- c_binding/include/libstoragemgmt/libstoragemgmt_types.h
- plugin/megaraid/megaraid.py
- plugin/ontap/ontap.py
- plugin/sim/simarray.py
- plugin/smispy/smis_disk.py
- python_binding/lsm/_data.py
- tools/lsmcli/data_display.py
* This patch set introduced new disk status -- STATUS_FREE to indicate
disk could be used for pool or assign as dedicated spare disk.
Changes in V2:
* Patch 6/7: Fix incorrect data assignment in MegaRAID plugin.
* Patch 5/7: Don't mark partner's disks as free disk in ONTAP plugin..
* Patch 7/7: Include SMI-S plugin support for STATUS_FREE using
vendor specific ways. Also come with STATUS_SPARE_DISK support.
Changes in V3:
* Patch 6/9: Remove the debug print line in simulator plugin.
* Patch 1/9: New patch. Change currnt git tree version as 1.2.
* Patch 2/9: New patch. Fix missing VOLUME_RAID_INFO capability of megaraid
plugin.
Changes in V4:
* Removed unrelated patches and submitted them in separate patch sets.
* Removed LSI MegaRAID SMI-S Disk.STATUS_FREE code as we have dedicate …
> [PATCH V4 0/6] Add new disk status: STATUS_FREE

- packaging/libstoragemgmt.spec.in
* The lsmd daemon should be restarted after this new plugin installed.
> RPM SPEC: Fix post install script of MegaRAID plugin.

- config/Makefile.am
- config/pluginconf.d/hpsa.conf
- configure.ac
- doc/man/Makefile.am
- doc/man/hpsa_lsmplugin.1.in
- packaging/libstoragemgmt.spec.in
- plugin/Makefile.am
- plugin/hpsa/Makefile.am
- plugin/hpsa/__init__.py
- plugin/hpsa/hpsa.py
- plugin/hpsa/hpsa_lsmplugin
- plugin/hpsa/utils.py
* The new hpsa plugin is based on HP binary tool -- hpssacli which
could be downloaded from:
http://downloads.linux.hp.com/SDR/project/spp/
* This patch set introduced these methods support to hpsa plugin:
* lsm.Client.systems()
* lsm.Client.pools()
* lsm.Client.volumes()
* lsm.Client.disks()
* lsm.Client.volume_raid_info()
* This patch set only coded and tested on 2 servers(Tony's and mine), a
automatic tests is running in our internal lab to test this plugin on more
HP SmartArray cards, will provide subsequent patch if found any bug.
Changes in V2:
* Patch 2/6:
* Fix missing '()' in _parse_hpssacli_output().
* Handle 'No controllers detected' error.
* Patch 6/6:
* Fix uninitialized variables in volume_raid_info().
* Add an extra check to raise PLUGIN_BUG when LD found with no PD found. …
> [PATCH V5 0/7] New HP SmartArray Plugin.

- README
- c_binding/include/libstoragemgmt/libstoragemgmt.h
- configure.ac
- doc/man/hpsa_lsmplugin.1.in
- doc/man/lsmcli.1.in
- doc/man/lsmd.1.in
- doc/man/lsmd.conf.5.in
- doc/man/megaraid_lsmplugin.1.in
- examples/plugin_example.c
- packaging/libstoragemgmt.spec.in
- tools/lsmcli/cmdline.py
* Update all maillist link to:
libstoragemgmt-devel@lists.fedorahosted.org
libstoragemgmt-users@lists.fedorahosted.org
* Update all upstream link to:
https://github.com/libstorage/libstoragemgmt/
Changes in V2:
* Use https://github.com/libstorage/libstoragemgmt/ as upstream link.
> Migration V2: git moved to github, maillist to fedorahosted

- examples/client_example.c
* Replace LSM_FLAG_RSVD with LSM_CLIENT_FLAG_RSVD.
* Add comments about configuration for autotool.
> C Example: Fix incorrect constant: LSM_FLAG_RSVD

- c_binding/include/libstoragemgmt/libstoragemgmt.h
- c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
- c_binding/include/libstoragemgmt/libstoragemgmt_error.h
- c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
- c_binding/include/libstoragemgmt/libstoragemgmt_types.h
- c_binding/lsm_convert.cpp
- c_binding/lsm_convert.hpp
- c_binding/lsm_mgmt.cpp
- c_binding/lsm_plugin_ipc.cpp
- doc/man/lsmcli.1.in
- plugin/hpsa/hpsa.py
- plugin/megaraid/megaraid.py
- plugin/ontap/ontap.py
- plugin/sim/simarray.py
- plugin/sim/simulator.py
- plugin/simc/simc_lsmplugin.c
- python_binding/lsm/_client.py
- python_binding/lsm/_common.py
- python_binding/lsm/_data.py
- test/cmdtest.py
- test/plugin_test.py
- test/tester.c
- tools/bash_completion/lsmcli
- tools/lsmcli/cmdline.py
- tools/lsmcli/data_display.py
* Putting two patch sets into one. As `pool_member_info()` patch set is
just preparation for `volume_raid_create()` patch set. It's better to
explain design choice with both.
* New method `pool_member_info()` to query pool member information:
* RAID type
* Member type: disk RAID pool or sub-pool.
* Members: disks or parent pools.
* New method `volume_raid_create()` to create RAID group volume.
* New method `volume_raid_create_cap_get()` to query RAID group volume create
supported RAID type and strip sizes.
* Design notes:
* Why we need pool_member_info() when we already have volume_raid_info()?
The `pool_member_info()` is focus on RAID disk or sub-pool layout.
The `volume_raid_info()` is focus on providing information about host
I/O performance and availability(raid).
* Why don't create …
> [PATCH V6 00/18] Pool RAID info query and hardware RAID volume creation.

- daemon/lsm_daemon.c
* On Debian 8, in plugin search path '/usr/bin', there is a symbolic linki
```
[fge@Gris-Laptop daemon]$ ls -l /usr/bin/X11
lrwxrwxrwx 1 root root 1 May  2 22:52 /usr/bin/X11 -> .
```
The stat() will treat it as an folder and scan it again which create
a infinity loop scan.
* Changing stat() to lstat() could fix this as lstat() does not follow
the symbolic link which skip the scan in it.
> lsmd: Fix a possible infinity loop on plugin search.

- c_binding/lsm_mgmt.cpp
- plugin/smispy/dmtf.py
- plugin/smispy/smis_vol.py
- python_binding/lsm/_data.py
- test/plugin_test.py
- test/tester.c
* After review SPC-3 and SPC-4 document and udev source code, I noticed the
incorrect definition of our Volume.vpd83.
Changes in V4:
* Patch 4/4: Fix None.lower() error in SMI-S plugin.
Changes in V5:
* Patch 1/4: Remove extra strlen() call by save its return in
lsm_volume_vpd83_verify() of lsm_mgmt.cpp.
> [PATCH V5 0/4] Volume VPD 83 Fix.

- plugin/sim/simarray.py
Issue:
When old state file is not an valid sqlite database, user will
get this confusing error:
PLUGIN_BUG(2): Got unexpected error: file is encrypted or is not a
database
Root cause:
DatabaseError is not well take care when loading state file.
Fix:
Raise ErrorNumber.INVALID_ARGUMENT error for sqlite3.DatabaseError
when loading state file.
Test:
dd if=/dev/urandom of=/tmp/lsm_sim_data bs=1M count=1
lsmcli ls -u sim://
> Simulator Plugin: Fix incorrect error message on incompatible state file

- c_binding/lsm_plugin_ipc.cpp
- python_binding/lsm/_common.py
* For error message like:
```
NO_SUPPORT(153): UNA Data: UNA
^^^^^^^^^^^^^
```
Root cause:
It is generated by `lsm_plugin_ipc.cpp error_send()`.
Fix:
Change to "Plugin didn't provide error message" and empty string to be
more human friendly.
* For error message like:
```
NO_SUPPORT(153): No support Data:
^^^^^
```
Root cause:
It is generated by `_common.py LsmError.__str__()`.
Fix:
Check whether data string is empty before adding "Data:" prefix.
> Fix issue #19: remove unnecessary error string.

- NEWS
- configure.ac
- packaging/libstoragemgmt.spec.in
Plugin Test results (RHEL 7 x86_64):
* EMC VNX SMI-S: PASS
* NetApp ONTAP: PASS
* Targetd: PASS for block methods. The fs methods will fail due to upstream bug. https://github.com/libstorage/libstoragemgmt/issues/28
* EMC VMAX SMI-S: PASS except failure on `volume_replicate()`. https://github.com/libstorage/libstoragemgmt/issues/27
* Nstor 3 and 4: PASS
* LSI MegaRAID: PASS
* HP SmartArray: PASS
> V1.2 release

- packaging/daemon/lsm-tmpfiles.conf
Fixes:
Jun 22 15:04:26 localhost.localdomain systemd[1]: Starting libstoragemgmt plug-in server daemon...
Jun 22 15:04:26 localhost.localdomain audit[1753]: <audit-1400> avc:  denied  { dac_override } for  pid=1753 comm="lsmd" capability=1  scontext=system_u:system_r:lsmd_t:s0 tcontext=system_u:system_r:lsmd_t:s0 tclass=capability permissive=0
Jun 22 15:04:26 localhost.localdomain lsmd[1753]: Unable to access socket directory /var/run/lsm/ipc, errno= 13
Jun 22 15:04:26 localhost.localdomain systemd[1]: libstoragemgmt.service: main process exited, code=exited, status=1/FAILURE
Should allow the daemon to run as root or as libstoragemgmt user.
> Fix: selinux dac_override

- plugin/megaraid/megaraid.py
1. Fix incorrect controller ID check in `volume_raid_create()`.
2. Fix pools() method on JBOD or no volume configured.
3. Include user define volume name in volumes() returns.
> MegaRAID Plugin fixes.

- plugin/hpsa/hpsa.py
* The output of hpssacli contains incorrect indented section which
cause 'duplicate line' PLUGIN_BUG error. To fix it, we only
parse required section.
* Add more comments to explain the workflow of parsing hpssacli output.
* Tested on SmartArray with and without disk enclosure.
Changes in V2:
* Fix spell errors.
> HP SmartArray plugin: Improve hpssacli output parsing algorithm.

- .travis.yml
- Makefile.am
* Patch 1/2 is to allow 'make distcheck' to run without libmicrohttpd.
The travis-ci.org is using Ubuntu 12.04 which is shipping old libmicrohttpd.
> Enable travis-ci test.

- .travis.yml
* Since required packages has been added to whitelist, we are ready to
use container(sudo: false) way for test.
> Travis-CI: Use container for test.

- plugin/targetd/targetd.py
Bug fix for volume_unmask and replaced the exception handlers with a common one that maps errors from targetd to error codes with libStorageMgmt with default messages if applicable. This
way we don't need to have a bunch of if/else statements in the exception handlers.
Note: I added a variable so if a caller wants to get the exception to evaluate
they can.
> Bug fix and simplify targetd error paths

- AUTHORS
- c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
- c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
- c_binding/include/libstoragemgmt/libstoragemgmt_systems.h
- c_binding/lsm_convert.cpp
- c_binding/lsm_datatypes.cpp
- c_binding/lsm_datatypes.hpp
- configure.ac
- plugin/hpsa/hpsa.py
- plugin/megaraid/megaraid.py
- plugin/sim/simarray.py
- plugin/sim/simulator.py
- plugin/simc/simc_lsmplugin.c
- python_binding/lsm/_data.py
- test/plugin_test.py
- test/runtests.sh
- test/tester.c
- tools/lsmcli/cmdline.py
- tools/lsmcli/data_display.py
~~* Please don't commit for these reason, TODO list:
* Tested on real hardware
* Check memory leak or etc.
* Split into small patches.
* Update license lines.~~
* Python part:
* Add new optional argument for `System.__init__()`.
* C part:
* ~~Plugin: `lsm_system_record_alloc_v1_3()` with `fw_ver` string.~~
* Plugin: `lsm_system_fw_version_set()`
* Client: `lsm_system_fw_version_get()`
* Misc:
* Increase version in configure.ac to 1.3.
* ~~Add empty struct for 1.3 C plugin interface -- `lsm_register_plugin_v1_3()`.~~
* Fix runtest.sh compatible issue with lsmenv.
* Included license of Joe@HP Enterprise.
> New API for retrieving system firmware version.

- plugin/hpsa/hpsa.py
HP SmartArray plugin: Add support for listing disks from an HPSA controller in HBA mode.
Signed-off-by: Blaine Gardner <blaine.gardner@hpe.com>
> HP SmartArray plugin: add support for listing disks in HBA mode

- plugin/ontap/ontap.py
- test/plugin_test.py
* Run the volume/LUN existence check before checking RAID information.
Changes since V1:
* Fix PEP8 'ontap.py:1310:62: E703 statement ends with a semicolon'
* Add test for volume_raid_info()
> [PATCH V2 0/2] ONTAP Plugin: Handle NOT_FOUND_VOLUME error in volume_raid_info().

- c_binding/include/libstoragemgmt/libstoragemgmt.h
- c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
- c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
- c_binding/lsm_datatypes.hpp
- c_binding/lsm_mgmt.cpp
- c_binding/lsm_plugin_ipc.cpp
- doc/man/lsmcli.1.in
- plugin/hpsa/hpsa.py
- plugin/sim/simarray.py
- plugin/sim/simulator.py
- plugin/simc/simc_lsmplugin.c
- python_binding/lsm/_client.py
- python_binding/lsm/_data.py
- test/cmdtest.py
- test/plugin_test.py
- test/tester.c
- tools/lsmcli/cmdline.py
Hopefully this one is less controversial. These two patches allow you to enable and disable LEDs behind logical volumes on a Smart Array (and I assume other controllers, but I don't know the other plugins well enough to implement for them). Take a look lemme know what you think.
> Add volume-ident-led-* support for volumes

- .travis.yml
- c_binding/Makefile.am
- c_binding/include/libstoragemgmt/Makefile.am
- c_binding/include/libstoragemgmt/libstoragemgmt.h
- c_binding/include/libstoragemgmt/libstoragemgmt_scsi.h
- c_binding/lsm_scsi.c
- configure.ac
- packaging/libstoragemgmt.spec.in
- python_binding/Makefile.am
- python_binding/lsm/__init__.py
- python_binding/lsm/_scsi.c
- test/cmdtest.py
- test/runtests.sh
- test/tester.c
- tools/lsmcli/cmdline.py
- tools/lsmcli/data_display.py
- tools/lsmenv
- tools/utility/check_const.pl
* API for querying scsi disk paths from VPD83 ID.
```
C:
int lsm_scsi_disk_paths_of_vpd83(const char *vpd83, 
lsm_string_list **sd_path_list, 
lsm_error **lsm_err)
Python:
lsm.SCSI.disk_paths_of_vpd83(vpd83)
```
* lsmcli changes: add "Disk Paths", example:
```
ID           | Name  | SCSI VPD 0x83    | Size       | Disabled | Pool ID       | System ID | Disk Paths
--------------------------------------------------------------------------------------------------------
VOL_ID_00001 | test  | 53333330000007d0 | 1073741824 | No       | POOL_ID_00001 | sim-01    | /dev/sda
|       |                  |            |          |               |           | /dev/sdf
|       |                  |            |          |               |           | /dev/sdh
|       |                  |            | …
```
> [PATCH V9] New function for SCSI disk path matching.

- plugin/megaraid/megaraid.py
Use `SCSI NAA Id` property for volume VPD83.
This feature only valid with storcli 1.18.05 or later version.
Test results:
```
[fge@megadeth megaraid]$ sudo lsmenv mega lsmcli lv -s
Device alias: mega
URI: megaraid://
lsmcli lv -s
------------------------------------------------
ID            | SV51929674:VD0                  
Name          | VD 0                            
SCSI VPD 0x83 | 600605b00a5796201e272bad49e24206
Block Size    | 512                             
Block Count   | 3905945600                      
Size          | 1999844147200                   
Disabled      | No                              
Pool ID       | SV51929674:DG0                  
System ID     | SV51929674                      
Disk Paths    | /dev/sdan …
```
> MegaRAID plugin: Add volume VPD83 support.

- plugin/megaraid/megaraid.py
Three fixes for MegaRAID plugin on disk querying.
* Remove check on 'Other Error Count' which is not documented and incorrect on disk status.
* Fix incorrect disk status on JBOD disk.
* Fix incorrect disk status query.
> Fixes for MegaRAID disks.

- c_binding/Makefile.am
- c_binding/include/libstoragemgmt/Makefile.am
- c_binding/include/libstoragemgmt/libstoragemgmt.h
- c_binding/include/libstoragemgmt/libstoragemgmt_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
- c_binding/lsm_local_disk.c
- c_binding/lsm_scsi.c
- packaging/libstoragemgmt.spec.in
- plugin/hpsa/hpsa.py
- python_binding/Makefile.am
- python_binding/lsm/__init__.py
- python_binding/lsm/_clib.c
- python_binding/lsm/_local_disk.py
- python_binding/lsm/_scsi_clib.c
- test/test_include.sh
- test/tester.c
- tools/lsmcli/cmdline.py
Rename `lsm_scsi_xxx` to `lsm_local_disk_xxx` as we support ATA protocol disks also.
In the future, we might also support NVMe disks as well.
Include other fixes:
* Fix constant check.
* Eliminate duplicate code by using some C macros.
* Split large functions to smaller one in `lsm_scsi_vpd83_of_disk_path()`.
> API rename: lsm_scsi_xxx to lsm_local_disk_xxx

- plugin/hpsa/hpsa.py
The Smart Array plugin was missing the SYS_MODE_GET Capability, even though it clearly supports the feature and is collecting the data.
> hpsa.py: Add SYS_MODE_GET to capabilities list

- test/plugin_test.py
The automated tests that run in the lab use stderr for generic
messaging and stdout to report execution timings.  As the unit
test prints to stderr this all works fine, except when I added
some print calls for warnings on the cleanup change in
a542eb2b04b4f8d07a2f320d965ce30fe8bfd1fe.  This caused the
automated tests to fail as we have invalid text in stdout which
was causing the yaml parser to fail.
Note(s):
- 2 of the arrays are returning errors during clean-up
- This change tested on all arrays in the lab
> plugin_test.py: Only write messages to stderr

- plugin/hpsa/hpsa.py
Some older Smart Arrays and more recent Smart Arrays with old firmware will fail to report a controller mode. Assume RAID mode for all these devices, which is a fair assumption on Linux.
Fixes #118 
> HPE Smart Array: Older controllers don't report mode

- c_binding/include/libstoragemgmt/libstoragemgmt_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_error.h
- doc/doxygen.conf.in
Updated libstoragemgmt_error.h enum documentation comments to fix Doxygen output. Updated error message of function lsm_disk_record_free in file libstoragemgmt_disk.h to refer to error code enum. Updated doxygen.conf to list enum numerical values in a manner easier for users to read.
Signed off by: Blaine Gardner <blaine.gardner@hpe.com>
> Update libstoragemgmt_error documentation

- c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
- c_binding/include/libstoragemgmt/libstoragemgmt_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_error.h
- c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
- c_binding/include/libstoragemgmt/libstoragemgmt_types.h
- c_binding/lsm_convert.cpp
- c_binding/lsm_datatypes.cpp
- c_binding/lsm_datatypes.hpp
- c_binding/lsm_local_disk.c
- doc/man/lsmcli.1.in
- plugin/hpsa/hpsa.py
- plugin/megaraid/megaraid.py
- plugin/sim/simarray.py
- plugin/simc/simc_lsmplugin.c
- python_binding/lsm/_clib.c
- python_binding/lsm/_common.py
- python_binding/lsm/_data.py
- python_binding/lsm/_local_disk.py
- test/cmdtest.py
- test/plugin_test.py
- test/tester.c
- tools/lsmcli/cmdline.py
- tools/lsmcli/data_display.py
Hightlights:
* ~~Query local disk rotation speed -- `lsm_scsi_rpm_of_disk_path()`.~~
* Query local disk rotation speed -- `lsm_local_disk_rpm_get()`.
* ~~Query local disk link type -- `lsm_scsi_link_type_of_disk_path()`.~~
* Query local disk link type -- `lsm_local_disk_link_type_get()`.
* ~~Use macro _wrapper() to remove duplicate code in `_scsi_clib.c`.~~ Already in master.
* ~~New lsmcli command -- `lsmcli lsd` to list all local scsi disks.~~
* New lsmcli command -- `lsmcli ldl` to list all local scsi disks.
FAQ:
* Why not use udev for RPM which does not need root privilege?
Udev does not support SAS disk RPM query yet.
Should we create a patch to udev or use this SCSI standard way?
* Why need root privilege?
Required by SGIO IOCTL. 
If kernel could expose more VPD pages (like 0xb1and …
> [PATCH V7 0/20] Querying disk rotation speed and link type

- c_binding/include/libstoragemgmt/libstoragemgmt_types.h
- plugin/hpsa/hpsa.py
- python_binding/lsm/_client.py
This attempts to address #106. All names are negotiable, but let me know if the concept is acceptable or unacceptable. 
From my perspective, pros:
* keeps the code quite simple
* prevents adding APIs for slight tweaks to existing APIs
* remains extensible and can be applied to non-HPE tech
cons:
* some flags may not map to all systems. How should that be handled and/or messaged to the user?
As always, thoughts are appreciated. This is the last feature I need in 1.3, once this and all outstanding feature pulls go in I think we're in very good shape for all use cases I'm trying to address.
> libstoragemgmt flags: add flags to provide volume creation options

- plugin/hpsa/hpsa.py
Lemme know what you guys think about this one for my volume reenable requirement, @tasleson and @cathay4t. My only concern is if a user will know that they are able to reenable a volume, but I suppose the workflow would be:
-assess pool health, discover that a pool is failed
-assess disk health, figure out which disk needs to be replaced (likely via Port:Box:Bay location)
-physically replace the device
-assess disk health again, if disks are all healthy but pool is still marked as unhealthy, attempt to reenable the volume provisioned from that pool
Thanks!
> HPE Smart Array: Add support for volume_enable to Smart Array

- c_binding/include/libstoragemgmt/libstoragemgmt.h
- c_binding/include/libstoragemgmt/libstoragemgmt_accessgroups.h
- c_binding/include/libstoragemgmt/libstoragemgmt_blockrange.h
- c_binding/include/libstoragemgmt/libstoragemgmt_capabilities.h
- c_binding/include/libstoragemgmt/libstoragemgmt_common.h
- c_binding/include/libstoragemgmt/libstoragemgmt_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_error.h
- c_binding/include/libstoragemgmt/libstoragemgmt_fs.h
- c_binding/include/libstoragemgmt/libstoragemgmt_hash.h
- c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_nfsexport.h
- c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
- c_binding/include/libstoragemgmt/libstoragemgmt_pool.h
- c_binding/include/libstoragemgmt/libstoragemgmt_snapshot.h
- c_binding/include/libstoragemgmt/libstoragemgmt_systems.h
- c_binding/include/libstoragemgmt/libstoragemgmt_targetport.h
- c_binding/include/libstoragemgmt/libstoragemgmt_types.h
- c_binding/include/libstoragemgmt/libstoragemgmt_volumes.h
Updated all libstoragemgmt_*.h header doxygen documentation to reference LSM_ERR_<reason> enum. Also fixed all comments of form /**^ comment */ which were below their intended items to be above them.
Signed off by: Blaine Gardner <blaine.gardner@hpe.com>
> Updated LSM_ERR_<reason> documentation.

- plugin/smispy/dmtf.py
- plugin/smispy/smis.py
- plugin/smispy/smis_ag.py
- plugin/smispy/smis_cap.py
- plugin/smispy/smis_common.py
- plugin/smispy/smis_disk.py
- plugin/smispy/smis_pool.py
- plugin/smispy/smis_sys.py
- plugin/smispy/smis_vol.py
- plugin/smispy/smispy_lsmplugin
- plugin/smispy/utils.py
- test/plugin_test.py
This PR addresses the following issues:
1. We were getting errors on one of the SMI-S system in the lab.  Added the case where CopyType ==  dmtf.ST_CONF_CAP_COPY_TYPE_UNSYNC_ASSOC we will then do a call to `ModifyReplicaSynchronization` to return to storage pool (19).  Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1323789
2. Capability was incorrect as we were comparing a function address to an integer
3. On volume delete we need to make sure volume is not masked before we try to delete it, so that we can return the correct error code instead of a plugin bug exception
4. Misc. pep8 clean-up, network error handling and code clean-up
> smispy plugin: Numerous improvements

- c_binding/Makefile.am
- c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
- c_binding/libses.c
- c_binding/libses.h
- c_binding/libsg.c
- c_binding/libsg.h
- c_binding/lsm_local_disk.c
- c_binding/utils.c
- c_binding/utils.h
- doc/man/lsmcli.1.in
- python_binding/lsm/_clib.c
- python_binding/lsm/_local_disk.py
- test/cmdtest.py
- test/tester.c
- tools/bash_completion/lsmcli
- tools/lsmcli/cmdline.py
* Only support SES(SCSI Enclosure Service) yet.
* New functions:
* C:
* `lsm_local_disk_ident_led_on()`
* `lsm_local_disk_ident_led_off()`
* `lsm_local_disk_fault_led_on()`
* `lsm_local_disk_fault_led_off()`
* Python:
* `lsm.LocalDisk.ident_led_on()`
* `lsm.LocalDisk.ident_led_off()`
* `lsm.LocalDisk.fault_led_on()`
* `lsm.LocalDisk.fault_led_off()`
* Tested on mpt2sas and hpsa enclosure.
> [PATCH V3 0/7]  Library API: Controlling IDENT/FAULT LED of local disk.

- c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
- c_binding/lsm_local_disk.c
- packaging/libstoragemgmt.spec.in
Problem:
When running in fakeroot, lsm_local_disk_list() might indicate the
existence of '/dev/sda' while lsm_ident_led_on() fail with
NOT_FOUND_DISK error.
Root cause:
The fakeroot might only have /sys mounted while /dev/ is not.
Fix:
Make sure the file '/dev/sdX' exists before add it to return list.
Also include a extra patch to remove unstable note on 1.3 plugin interface.
> Fix RHEL/Fedora mock build test failure.

- c_binding/lsm_local_disk.c
- c_binding/utils.c
- configure.ac
- test/runtests.sh.in
* Fix a bug introduced by PR #150.
* Add new configure option to skip memory leak check test.
* Fix lsm_local_disk_vpd83_search() for RHEL/Fedora mock build.
> Misc fixes

- Makefile.am
- configure.ac
- test/Makefile.am
* Remove the old configure option '--disable-build-c-unit' as it will
fail 'make check'.
* Add new configure option './configure --without-test' to skip all
test cases and their requirement check.
* Add 'ps' into requirement as 'test_include.sh' needs it.
> Autotools: New configure option '--without-test'

- c_binding/lsm_local_disk.c
Please check https://bugzilla.redhat.com/show_bug.cgi?id=1346898 for detail.
This patch set is trying to use udev as fallback if sysfs vpd83 not available.
> Bug fix for sysfs vpd83 file not accessable.

- tools/lsmcli/cmdline.py
Problem:
The 'lsmcli job-status --job <JOB_ID>' will fail on volume
creation job due to missing 'sd_paths' property.
Fix:
Call _add_sd_paths() before invoking display_data().
> Fix lsmcli job-status command on volume creation job.

- test/plugin_test.py
Problem:
Got blow error when run 'make check' on RHEL/Centos 6.
ERROR: test_invalid_uri (__main__.TestPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/tmp/10441/bin//plugin_test.py", line 1582, in test_invalid_uri
with self.assertRaises(lsm.LsmError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
----------------------------------------------------------------------
Root cause:
'with self.assertRaises(lsm.LsmError)' is only supported by
python 2.7+ while RHEL6 only ships python 2.6
Fix:
Change to:
self.assertRaises(lsm.LsmError, lsm.Client,
"ontap//root@na-sim", "some_password")
> Fix 'make check' on RHEL 6(python 2.6)

- tools/lsmcli/cmdline.py
Problem:
C plugin will raise/return INVALID_ARGUMENT error on this command:
lsmcli volume-replicate-range --src-vol VOL_ID_00001 \
--dst-vol VOL_ID_00002 --rep-type CLONE \
--src-start 0 --dst-start 0 --count 100 -f
Root cause:
lsmcli use string instead of int/long to initialize BlockRange
object which cause value_to_block_range() in C library failed at
range["src_block"].asUint64_t()
Fix:
Convert string provided by argument parser to int.
> Bug fix: lsmcli volume-replicate-range will fail on C plugin.

- c_binding/libses.c
- c_binding/libsg.c
- c_binding/lsm_local_disk.c
- c_binding/utils.h
- python_binding/lsm/_local_disk.py
- tools/lsmcli/cmdline.py
Fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=1360177
Fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=1361107
Changes:
* Check SCSI sense for error. In above bug, ioctl still return 0 even when certain VPD is not supported.
* Include SCSI sense information in error message.
* Fix regression of SES functions caused by f786fa4a0dcb4afed1cf48f4b7780ed73956af8b
> Include SCSI sense support and fix regression of SES functions.

- plugin/hpsa/hpsa.py
There was a mistake here that I ran into on an H240 Smart Array card in RAID mode. I used the wrong naming scheme, missed it because my hardware was not available until recently. 
Signed-off-by: Joe Handzik <joseph.t.handzik@hpe.com>
> hpsa: Update cacheless variable

- c_binding/lsm_convert.cpp
Problem:
lsm_disk_vpd83_set() does works when transferring data to Python
client API(like lsmcli).
Root cause:
disk_to_value() does not handle vpd83.
> C library: Fix missing vpd83 optional property of disk.

- c_binding/lsm_convert.cpp
Problem:
For NFS exports returned by C plugin, the
LSM_NFS_EXPORT_ANON_UID_GID_NA is incorrectly converted to
'2 ** 64 -1' in JSON which failed python API, example:
===
[fge@Gris-Laptop lsm]$ lsmenv simc lsmcli list --type exports -s
Device alias: simc
URI: simc://
lsmcli list --type exports -s
------------------------------------
ID            | EXP_ID_00001
FileSystem ID | FS_ID_00001
Export Path   | /nfs_exp_5076931fa
Auth Type     |
RW Hosts      | localhost
Anonymous UID | 18446744073709551615
Anonymous GID | 18446744073709551615
Options       |
------------------------------------
===
Root cause:
The anon_uid/anon_gid is uint64_t in C API(both client and plugin),
which convert LSM_NFS_EXPORT_ANON_UID_GID_NA(-1) to
UINT64_MAX('2 ** 64 - 1').
Fix:
Make sure nfs_export_to_value() in …
> Fix anon_uid/anon_gid from C plugin to Python API.

- tools/lsmcli/cmdline.py
On Python 2.6, lsmcli will failed with error:
```
ValueError: zero length field name in format
```
Adding field numbers fixed this issue.
> lsmcli: Fix running on python 2.6.

- c_binding/lsm_convert.cpp
Fix the leftover -2 value handler in lsm_convert.cpp for uid/gid.
Please check https://github.com/libstorage/libstoragemgmt/pull/184 for detail.
> C library: Fix LSM_NFS_EXPORT_ANON_UID_GID_ERROR in lsm_convert.cpp

- c_binding/lsm_mgmt.cpp
Problem:
When C client API passing LSM_NFS_EXPORT_ANON_UID_GID_NA(-1) to
plugin, it will be converted to some large number[1].
Fix:
Change lsm_mgmt.c to use -1 or -2 for JSON in IPC.
[1]: On RHEL 7, it will be UINT64_MAX - 1, on RHEL 6, it will be
INT64_MAX - 1. For C++ code, I have no idea why the difference.
> C library: Fix anon_uid/anon_gid from C client to plugin.

- plugin/hpsa/hpsa.py
Since status_info may contain other information besides status, add
clarity to existing info. The form follows that implemented by the
system mode addition, and will now look like below example:
'status=['OK']'
If there is an unknown system mode, it will be changed as below example:
'status=['OK'] mode=['Unknown Mode']'
This will make it easy for other applications to parse and interpret
the outputs.
> Improve readability of status_info from HPSA

- plugin/hpsa/utils.py
- plugin/megaraid/utils.py
This is necessary to force stdout and stderr to be strings instead of byte
sequences. The code was written assuming that was always true, which it had
been until python3 support was attempted.
Signed-off-by: Joe Handzik <joseph.t.handzik@hpe.com>
> Set universal_newlines=True for Popen calls in hpsa and megaraid plugin utils.py

- plugin/hpsa/hpsa.py
There is a bug in the HPSSACLI parsing code that will not get the
key-value pair for (a) properties that are at the end of a section or
(b) properties that appear alone.
In testing, controller status may appear alone and needs to be
whitelisted by adding it to the required sections variable. In the
event that cache status or battery status appear at the end of the
section, I also added those to the whitelist. This fix is non-ideal,
but it needs to appear in the next release, which is very soon.
This issue may rear its head again later, so an overhaul of the
HPSSACLI parsing routine may be appropriate.
Signed-off-by: Blaine Gardner <blaine.gardner@hpe.com>
> Add controller, cache, and battery statuses to required sections

- plugin/hpsa/hpsa.py
Status info is currently reported in such a way that
'status=[OK]status=[OK]status=[OK]' may be returned.
Instead of 'status', report the name of the property in quotes. Also
add white space for readability. New reporting should be:
'"Controller Status"=[OK] "Cache Status"=[OK] "..."=[...]'
Fixes #212
Signed-off-by: Blaine Gardner <blaine.gardner@hpe.com>
> Add specificity to hpsa plugin status info

- tools/lsmcli/cmdline.py
While functional, there's no reason (as far as I can tell) to include these extra spaces. 
> cmdline.py: Remove unnecessary whitespace

- plugin/hpsa/hpsa.py
Newer versions of hpssacli/ssacli will output a "Logical/Physical Block Size" element rather than the previously supported "Native Block Size". Support both options.
Fixes #223 
> plugin/hpsa: Support Logical/Physical Block Size

- .gitattributes
- plugin/megaraid/megaraid.py
- test/plugin_test.py.in
- Fake timeout support in order to pass plugin test.
- Add missing `VOLUME_CACHE_INFO` capability.
Note: If you edit the pull request text section, you will get the unit tests to re-run.  Not sure if this is good or not, but it does help with testing CI infrastructure.
> MegaRAID plugin: Fake timeout support and add missing capability.

- c_binding/libses.c
- c_binding/libses.h
- c_binding/libsg.c
- c_binding/libsg.h
- c_binding/lsm_local_disk.c
- c_binding/utils.c
- c_binding/utils.h
- plugin/simc/db.c
- plugin/simc/db.h
- plugin/simc/db_table_init.h
- plugin/simc/fs_ops.c
- plugin/simc/fs_ops.h
- plugin/simc/mgm_ops.c
- plugin/simc/mgm_ops.h
- plugin/simc/nfs_ops.c
- plugin/simc/nfs_ops.h
- plugin/simc/ops_v1_2.c
- plugin/simc/ops_v1_2.h
- plugin/simc/ops_v1_3.c
- plugin/simc/ops_v1_3.h
- plugin/simc/san_ops.c
- plugin/simc/san_ops.h
- plugin/simc/utils.c
- plugin/simc/utils.h
- plugin/simc/vector.c
- plugin/simc/vector.h
- python_binding/lsm/_clib.c
According to https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility
LGPL v3.0+ is not compatible with GPL 2.0 only application.
Hence we relicense to LGPL v2.1+ for better compatibilities.
> Change license to "LGPL v2.1 or later".

- c_binding/Makefile.am
- c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_types.h
- c_binding/libata.c
- c_binding/libata.h
- c_binding/libfc.c
- c_binding/libfc.h
- c_binding/libiscsi.c
- c_binding/libiscsi.h
- c_binding/libsas.c
- c_binding/libsas.h
- c_binding/libsg.c
- c_binding/libsg.h
- c_binding/lsm_local_disk.c
- c_binding/utils.c
- c_binding/utils.h
- python_binding/lsm/_clib.c
- python_binding/lsm/_data.py
- python_binding/lsm/_local_disk.py
- test/tester.c
- tools/lsmcli/cmdline.py
- tools/lsmcli/data_display.py
C API: 
```c
int lsm_local_disk_link_speed_get(const char *disk_path,
uint32_t *link_speed,
lsm_error **lsm_err);
```
Python API: `lsm.LocalDisk.link_speed_get()`.
The returned link speed is in Mbps, for example, '3.0 Gbps' is `3000`.
Current, we have FC, SAS, SATA and iSCSI supported.
> Local disk link speed query

- tools/udev/scan-scsi-target.c
* Issue:
Got failure on s390x:
scan-scsi-target.c:90:2: error: comparison is always true due to limited
range of data type [-Werror=type-limits]
* Root cause:
The error is on these lines:
char c;
...
while ((c = getopt_long(argc, argv, "rh", longopts, NULL)) != -1) {
On non-x86 platform, char is unsigned. Which makes the (c != -1)
always true.
* Fix:
Take return of getopt_long() as int.
> udev: Fix gcc warning on non-x86 platform.

- c_binding/libses.c
- plugin/simc/ops_v1_2.c
* Should use strlen() instead of sizeof() for calculate string length.
* Fix the gcc warning on fallthrough switch.
> Misc fixes found by Fedora rawhide gcc

- c_binding/libsg.c
There are four bytes in the 'Information' portion of the structure, not three.
Fixes #259
> libsg: Fix fixed sense data structure

- test/trusted.yaml
Seems like we should trust the root repo...
> Update trusted.yaml to include libstorage

- doc/man/ontap_lsmplugin.1.in
- plugin/ontap/na.py
- plugin/ontap/ontap.py
```
Issue:
lsmcli  -u "ontap+ssl://root@na3170b.lab.bos.redhat.com" ls
NETWORK_ERROR(142): <urlopen error [SSL: UNSUPPORTED_PROTOCOL]
unsupported protocol
Root cause:
Some OS are removing openssl the support of SSLv2 and SSLv3.
Fix:
* When ONTAP filer is using SSLv2 or SSLv3, raise NO_SUPPORT error
and suggest user to enable TLS.
* New URI parameter 'ssl_verify=yes' to enable full SSL
verification, by default, we still ignore hostname check and
certification check.
* Updated manpage with guide to enable TLS on ONTAP filer and
explanation of new URI parameter 'ssl_verify=yes'.
* Use uri_parse() from lsm instead of urlparse().
```
> ONTAP plugin: SSL fix.

- c_binding/include/libstoragemgmt/libstoragemgmt_local_disk.h
- c_binding/include/libstoragemgmt/libstoragemgmt_types.h
- c_binding/libata.c
- c_binding/libata.h
- c_binding/libsg.c
- c_binding/libsg.h
- c_binding/lsm_local_disk.c
- python_binding/lsm/_clib.c
- python_binding/lsm/_data.py
- python_binding/lsm/_local_disk.py
- test/tester.c
- tools/lsmcli/cmdline.py
- tools/lsmcli/data_display.py
This patch adds the ability to query SMART Status for SAS and SATA drives via the local_disk APIs.
> lsm_local_disk: Add SMART Status query method

- tools/lsmcli/cmdline.py
```
Issue:
Got error when `lsmcli fs-snap-restore --force  --fs <FS_ID> --snap <SNP_ID`
against a NetApp ONTAP array:
INVALID_ARGUMENT(101): Invalid parameter combination 
Root cause:
In API definition, only when "files == None and all_files = True"
means all files on the file system are restored. The lsmcli set the
`files` to [] which is None.
Fix:
Fix lsmcli to use None for restoring the whole file system.
```
> lsmcli: Fix bug of fs-snap-restore when restoring the whole file system

- configure.ac
- doc/Makefile.am
- packaging/libstoragemgmt.spec.in
- plugin/sim/simarray.py
- test/runtests.sh.in
- test/test_include.sh
Test: Two new test cases for Python 2 and 3 interaction.
* Run python2 version of lsmcli test and plugin test with python3
version simulator plugin.
* Run python3 version of lsmcli test and plugin test with python2
version simulator plugin.
* These two tests will be run only when `--with-python3` configure
option is in use.
Also fixed some issue found by these tests.
> New test cases for Python 2 and Python3 interaction test.

- plugin/sim/simarray.py
- plugin/simc/db.c
- plugin/simc/db.h
- plugin/simc/db_table_init.h
- plugin/simc/san_ops.c
- test/plugin_test.py.in
```
Issue:
When deleting a volume created by `volume_raid_create()`, disks used
by this volume will also be deleted.
Root cause:
The `disks` table will remove the disks entry when owner pool delete.
The sql table line to blame is:
FOREIGN KEY(owner_pool_id)
REFERENCES pools(id) ON DELETE CASCADE );
Fix:
* Change to `ON DELETE SET DEFAULT`.
* Update disk `role` to NULL when deleting a HW RAID volume.
```
> Sim and simc plugin: Fix missing disks after volume_delete() on HW RAID volume

- doc/man/targetd_lsmplugin.1.in
- plugin/targetd/targetd.py
- python_binding/lsm/_common.py
Two new URI parameters have been added:
`no_ssl_verify=yes` = Disables all SSL certificate validation
`cert_file=<server certificate file >` = Certificate to use to verify server certificate
Targetd man page updated as well.
> Improve targetd plugin SSL certificate handling

- c_binding/libata.c
- c_binding/libsas.c
- c_binding/libses.c
- c_binding/libses.h
- c_binding/libsg.c
- c_binding/lsm_local_disk.c
```
Issue:
C local disks functions does not work on big-endian
system(s390x/ppc64/arm/etc).
Root cause:
Bit field has endian compatibility issue.
https://stackoverflow.com/questions/6043483/why-bit-endianness-is-an-issue-in-bitfields
Fix:
Use gcc macro to detect endianness and reorder the struct member
sequence. It's also the way used by linux kernel tcp module:
/usr/include/linux/tcp.h
```
> C library: Fix bit field endian compatibility issue

- c_binding/libata.c
- c_binding/libsas.c
- c_binding/libses.c
- c_binding/libses.h
- c_binding/libsg.c
- c_binding/lsm_local_disk.c
```
Issue:
Got this error of command `lsmcli ldl` against a Dell virtual
floppy:
LIB_BUG(1): BUG: Got incorrect VPD page code '80', should be 0x83
Root cause:
When query VPD83 of Dell virtual floppy, it returns a STANDARD
INQUIRY instead of VPD page, and this is not clarified by SCSI SPC-4
or later version.
[fge@dell-pe1950-06 ~]$ sudo sg_vpd --page=0x83 /dev/sdc -vvv -H
open /dev/sdc with flags=0x800
Device Identification VPD page:
inquiry cdb: 12 01 83 00 fc 00
duration=1 ms
inquiry: pass-through requested 252 bytes but got 36 bytes
invalid VPD response; probably a STANDARD INQUIRY response
First 32 bytes of bad response
00     00 80 00 01 1f 00 00 00  44 65 6c 6c 20 20 20 20    ........Dell
10     56 69 72 74 75 61 6c 20  20 46 6c 6f 70 70 79 20    Virtual  Floppy
fetching VPD page …
```
>  LocalDisk: Fix error on Dell virtual floppy

- c_binding/libsg.c
Clearly this path was never used in my testing. Checking the correct variable for assert.
> Fix assert bug in _fill_ata_regs_fixed

- .travis.yml
- deb_dependency
- packaging/libstoragemgmt.spec.in
- rh_rpm_dependency
- suse_rpm_dependency
- test/cmdtest.py.in
- test/docker_travis_test.sh
* Use Ubuntu Trusty(14.04 LTS).
* Use docker in travis for Fedora and Centos 7 test.
* Disable make check in rpm build to eliminate duplicate test.
> Travis CI: Use docker to run test on Fedora and Centos 7

- .travis.yml
It is now the default.
See: https://blog.travis-ci.com/2017-08-31-trusty-as-default-status.
Signed-off-by: mulhern <amulhern@redhat.com>
> Travis CI: Do not specify trusty distribution.

- c_binding/libses.c
- c_binding/libsg.c
- tools/lsmcli/cmdline.py
* sg kernel module is not auto-loaded on some(RHEL/Centos 7)
distribution, while bsg is mostly compiled(RHEL/Fedora/Ubuntu) into kernel.
So, we use /dev/bsg/<htbl_id> instead of /dev/sgX for SES functions.
* The bsg only support SG_IO v4(while sg only for V3), hence we have
new function `_sg_io_v4()` for that.
* Also ignore error of `lsmcli ldl`, fix issue #291.
> C library: Switch from sg kernel module to bsg.

- plugin/megaraid/megaraid.py
Background story is:
https://github.com/libstorage/libstoragemgmt/pull/307#issuecomment-332312221
This patch use random temperate folder to store the log of
storcli/perccli.
tasleson: CI Kick
> MegaRAID plugin: Use random temperate folder for log of storlci.

- c_binding/lsm_plugin_ipc.cpp
- configure.ac
* Change configure.ac to set gcc warnings flags in CPPFLAGS.
* Fix all warnings.
> Enable GCC warnings on CPP code also.

- c_binding/libsg.c
- tools/lsmcli/cmdline.py
Bug:    https://bugzilla.redhat.com/show_bug.cgi?id=1501367
Root cause:
```
Incorrect data size for VPD 0x89(ATA information).
The SPEC only allows 572(0x023c) bytes, we are requesting 0xffff
bytes.
```
Fix:
```
Change _sg_io_vpd() to set correct output data buffer size for
page 0x89(ATA infomation) and 0xb1(Block Device Characteristics).
```
CI Kick
Also add newline to every warning message of lsmcli on stderr.
> LocalDisk: Fix incorrect VPD query for 0x89 and 0xb1.

- c_binding/include/libstoragemgmt/libstoragemgmt.h
- c_binding/include/libstoragemgmt/libstoragemgmt_error.h
- plugin/nstor/nstor.py
- plugin/ontap/na.py
- plugin/ontap/ontap.py
- plugin/sim/simarray.py
- plugin/simc/fs_ops.c
- plugin/simc/san_ops.c
- python_binding/lsm/_common.py
- test/plugin_test.py.in
* New error for volume_delete()/fs_delete() when specified volume/fs ~~is~~
~~replication source~~ has child dependency.
* C:        `LSM_ERR_HAS_CHILD_DEPENDENCY`
* Python:   `lsm.ErrorNumber.HAS_CHILD_DEPENDENCY`
* Both simc and sim plugins are respecting this error now.
* Manpage of C API updated for this error.
* ONTAP plugin are respecting this error for fs_delete(). For
volume_delete(), it does not have child dependency, hence no error
will be raised.
* Add test case into plugin_test.py for this new error.
> New error for delete when volume/fs has child dependency

- plugin/megaraid/megaraid.py
* MegaRAID always enable read cache. Old code treat that as read ahead
cache which is not what we defined in API document.
* Fix the write cache set function to handle 'Cache I/O'.
* Inform user via volume_read_cache_policy_update(): read cache is
always enabled, if they are looking for read ahead cache setting, they
should use storcli/perccli.
> MegaRAID plugin: Fix cache information query.

- tools/use_cases/find_unused_lun.py
* Tested on:
* When disk has partition.
* When file system mounted.
* When LVM PV and VG created but no LV.
* When multipath enabled.
* Example output:
```bash
$ sudo ./find_unused_lun.py
LSMCLI_URI environment not defined, using 'local://'
Found free disk /dev/sdar, but not management by libstoragemgmt plugin
Found 1 free LUN(s):
{
"system_name": "LSI MegaRAID SAS 9286CV-8eCC PCI-E 00:81:00:00",
"name": "VD 0: test2",
"blk_paths": [
"/dev/sdb"
],
"id": "600605b00a579620215bbb2f4c2755b8",
"system_id": "SV51929674",
"wwid": "600605b00a579620215bbb2f4c2755b8"
}
```
Another example on NetApp LUN with multipath enabled:
```bash
[fge@el7r ~]$ sudo LSMCLI_PASSWORD=pass LSMCLI_URI=ontap://root@ip \
./find_unused_lun.py 
Found 1 free LUN(s):
{
"system_name": "na3170b", 
"name": "gris-lsm-test", …
```
> User case: Find unused LUN/Volume

- python_binding/lsm/_pluginrunner.py
Treat `socket.error` as client went away if plugin is registered.
Fixing bug: https://bugzilla.redhat.com/show_bug.cgi?id=1582458
> Python plugin runner: don't print socket error to syslog.

- tools/lsmcli/cmdline.py
* Python 3.7 introduced new reserved keywords -- `async` which happened
to be used in lsmcli. We change lsmcli to use `_async` instead.
> lsmcli: Fix required to run on python3.7

- debian/libstoragemgmt-tools.install
- debian/python-libstoragemgmt.install
- packaging/libstoragemgmt.spec.in
- tools/Makefile.am
According to Filesystem Hierarchy Standard(FHS) 3.0:
http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf
Section 4.4.2. Requirements:
`There must be no subdirectories in /usr/bin.`
Moved user case and sanity check tools to '/usr/libexec/lsm.d' folder
as that is suggested by FHS and Fedora.
> Filesystem Hierarchy Standard: Move tools to /usr/libexec/lsm.d folder.

- plugin/hpsa/hpsa.py
Since ssacli version 3.25, the 'Total Cache Size' is changed to number
based on GiB. Like below:
-   Total Cache Size: 1024 MB
-   Total Cache Memory Available: 816 MB
+   Total Cache Size: 1.0
+   Total Cache Memory Available: 0.8
This causes volume_raid_info() failed on unknown size string.
https://github.com/libstorage/libstoragemgmt/issues/340
Also fixed the running hpsa on python3 the dictview issue.
> HPSA plugin: Support ssacli version 3.25+

- c_binding/include/libstoragemgmt/libstoragemgmt_accessgroups.h
- c_binding/lsm_datatypes.cpp
- test/tester.c
This data was always available, just not exposed in C API.  It
was available in python API.
Fixes: https://github.com/libstorage/libstoragemgmt/issues/320
> C API: Add lsm_access_group_init_type_get

- configure.ac
Changes:
* Replace yajl with nlohmann/json for JSON handling.
* Bug fixes:
- Fix the file path of lsmd.conf manpage.
- HPSA plugin: Support ssacli version 3.25+.
- Filesystem Hierarchy Standard: Move tools to
/usr/libexec/lsm.d folder.
- scan-scsi-target: Fix compiling on gcc 8.2.
- Fix lsmcli on python 3.7.
- Handle 'Warning:' message in hpsa plugin
* Enhancements
- Add configure options for not including specified plugins
- Add lsm_access_group_init_type_get to C API
> New release: 1.7.0

- packaging/libstoragemgmt.spec.in
The plugin requires the /etc/exports.d directory that nfs-utils provides, it also requires the exportfs command provided by that package.
> Make nfs-plugin rpm require nfs-utils as per bz 1657407

- config/Makefile.am
Missed this when adding functionality to configure without
nfs plugin.
> config/Makefile.am: Use WITH_NFS

- doc/man/lsmcli.1.in
- tools/lsmcli/cmdline.py
When a user lists snapshots it is required that they supply a
filesystem.  A filesystem is specific to a given system, thus
allowing the user to constrain the search to a specific system
with --sys <sys_id> is redundant.
CI redo
> man: Remove SNAPSHOTS from optional --sys constraint

- plugin/arcconf/arcconf.py
issue: column 'Read Cache Percentage' data displayed is -1
fix: 'readCachePercentage' value is read from getconfigJSON and is displayed properly.
issue: column 'Info'  data displayed is "Controller Status"=[2] mode=[3]
fix: corresponding display string for 'status' and 'mode' is set. added 'slot' information as well
> Arcconf Plugin patch: Fix for 'Systems' function

- debian/libstoragemgmt-tools.install
/usr/libexec/lsm.d/*.py was included in both python-libstoragemgmt and libstoragemgmt-tools, removing from libstoremgmt-tools as it depends on python-libstoragemgmt.
> debian: fix duplicate files in packages

- plugin/megaraid/megaraid.py
Old MegaRAID cards can show disks with WWN==NA. It causes INVALID_ARGUMENT like below:
$ export LSMCLI_URI=megaraid://
$ sudo -E lsmcli ld
INVALID_ARGUMENT(101): Incorrect format of VPD 0x83 NAA(3) string: 'na', expecting 32 or 16 lower case hex characters
This patch overwrites VPD 0x83 value with an empty string if it has 'NA'.
> megaraid: avoid INVALID_ARGUMENT error when disk WNN is NA

- c_binding/libses.c
The PAGE LENGTH in the SES-3 spec is labelled 'n - 3' but that doesn't mean we should do PAGE LENGTH + 3 to get the buffer size as the 0 byte is being counted.
Fixes: https://github.com/libstorage/libstoragemgmt/issues/383
CI Kick
> Fix local-disk-*-led-* on final slot in SES list

- plugin/arcconf/arcconf.py
Adding support to get the raid capabilities supported as plugin test runner for 'volume-raid-create' is dependent on 'volume-raid-create-cap'
CI Redo 4
> Arcconf Plugin: Add 'volume-create-raid-cap' support

- plugin/arcconf/arcconf.py
As part of https://github.com/libstorage/libstoragemgmt/issues/374 . system id in disks was left out in previous PR.
> System id update in disks function

- daemon/lsm_daemon.c
Execute lsmd --help every time, The command will generate a process.
As a help I think that should not produce a process.
[root@localhost ~]# lsmd --help
libStorageMgmt plug-in daemon.
lsmd [--plugindir <directory>] [--socketdir <dir>] [-v] [-d]
--plugindir = The directory where the plugins are located
--socketdir = The directory where the Unix domain sockets will be created
--confdir   = The directory where the config files are located
-v          = Verbose logging
-d          = New style daemon (systemd)
[root@localhost ~]# ps -ef | grep lsmd
libstor+  3854     1  0 Oct21 ?        00:00:02 /usr/bin/lsmd -d
libstor+  6112     1  0 21:18 ?        00:00:00 lsmd --help
libstor+  6305     1  0 21:18 ?        00:00:00 lsmd --help
libstor+  6340     1  0 21:18 ?        00:00:00 lsmd --help …
> lsmd: optimization when execute lsmd help generate a process

- c_binding/libses.c
- c_binding/libsg.c
- c_binding/lsm_local_disk.c
- c_binding/utils.c
- c_binding/utils.h
- plugin/simc/simc_lsmplugin.c
Alpine linux does not have strerror_r.
Addresses https://github.com/libstorage/libstoragemgmt/issues/401
> Change strerror_r -> strerror_l

- NEWS
- configure.ac
* Compile fixes for Alpine Linux
- https://github.com/libstorage/libstoragemgmt/issues/403
- https://github.com/libstorage/libstoragemgmt/issues/402
- https://github.com/libstorage/libstoragemgmt/issues/401
* Don't orphan lsmd process when displaying help
- https://github.com/libstorage/libstoragemgmt/pull/399
> Prepare for new release

- plugin/arcconf/arcconf.py
This is regarding issue mentioned in libstorage#410
currently, once the volume is created, it's respective pool ID was searched with 'controllerID : VolumeID' instead of 'systemID : VolumeID'.
This is fixed with with fetching system ID and assigning correct pool ID
> volume-raid-create pool ID issue

- plugin/megaraid/megaraid.py
this fixes a small bug in the implementation of #375
> megaraid: correctly override vpd83 when WWN is NA

- .travis.yml
Getting the following error:
```
Package python-pywbem is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
sblim-wbemcli
```
> travis: Remove ubuntu:latest

- python_binding/lsm/_client.py
When the client detects that the service isn't running, instead
of stating try 'service libstoragemgmt start'  we will simply
state to start the service.  This avoids any confusion depending
on if the system uses systemd or other for service management.
> Change service err msg

- c_binding/libsg.c
- c_binding/libsg.h
Idea from sg3_utils; it's turned out that certain controllers
(Areca ARC-1680 series) cause timeouts and bus resets with longer
requested lengths in these commands.
Signed-off-by: Dan Mick <dmick@redhat.com>
CI Kick
> Use one-byte length for VPD inquiry commands

- c_binding/Makefile.am
- c_binding/libnvme.c
- c_binding/libnvme.h
- c_binding/lsm_local_disk.c
- configure.ac
- packaging/libstoragemgmt.spec.in
Add ability to check the health status for NVMe devices.
We are using the get log page admin command with log page
2 (smart/health information) and checking the critical warning
return byte.
> lsm_local_disk_health_status_get: Add NVMe health check

- c_binding/include/libstoragemgmt/libstoragemgmt_plug_interface.h
- c_binding/lsm_convert.cpp
- c_binding/lsm_datatypes.cpp
- c_binding/lsm_datatypes.hpp
- test/tester.c
This was missed in the original release.  Adding an additional
function to allow it to be utilized.
Resolves: https://github.com/libstorage/libstoragemgmt/issues/68
> c_binding: Add disk record plugin_data

- packaging/libstoragemgmt.spec.in
- plugin/sim_plugin/Makefile.am
When commit 63a9ec054ad4d00069aec76fb3aaba13aecec0f7 was done we
placed the python files in the arch specific python location. As
we package the simulator with the files that are in the arch
specific directory, these should be placed in that directory
structure too.
> Correct simulator plugin location

- configure.ac
- debian/python-libstoragemgmt.install
Python2.x is deprecated, thus it's a good idea to finally move to Python3.
I suggest these 2 initial fixes that still let you build 'as is' (i.e. don't break Python2 compatibility for Debian-like OS) but let you build for Python3, if you make some additional changes.  
I'd also like to suggest changes to build on Python3 by default but that should be in another PR, I think.
> Debian-like OS fixes for python3 builds

- c_binding/lsm_local_disk.c
Some devices will incorrectly return good status when we request
vpd page 0xb1.  However, the returned data is incorrect.  Instead
of reporting this as a library issue, we will report it as
not supported.
> lsm_local_disk_rpm_get: Return not supported, not library error

- .circleci/config.yml
- python_binding/lsm/_client.py
- python_binding/lsm/_transport.py
- test/docker_ci_test.sh
- tools/lsmcli/cmdline.py
- tools/smisping/smisping.py
When developing a new plugin it's helpful to not require the daemon to be
running.  Add a hidden argument  `--fork_plugin` that when specified allows the command line
to exec. the plugin directly.  Historically python plugins were easier
to develop as you can execute a python plugin directly from the command
line.  With this functionality it allows plugin developers an easier
time developing in other languages too.
> Add ability to fork plugin directly from lsmcli

- .circleci/config.yml
Circle CI has updated their base container kernel which supports
what we need to run fedora.
> Update fedora container to latest

- tools/udev/scan-scsi-target.c
If SCSI vports are used by adding them via NPIV by using the
vport_create file for an FC port:
```
```
This will create a virtual host at a higher index number than the
existing FC hosts. You can assign LUNs to these hosts just as you
would to the actual FC hosts. Assigning LUNs will result in a
unit attention of reported LUNs data has changed, which will have
this path from udev as the devpath.
/devices/pci0000:00/0000:00:03.0/0000:04:00.0/host6/vport-6:0-0/
host10/rport-10:0-2/target10:0:0/10:0:0:1
The existing scan-scsi-target will find the first instance of '/host'
and cause a rescan on host6 which is not where the ACL has actually
changed. The rescan should happen on the virtual host, host10 to get
the expected result.
> Handle udev events on SCSI vports

- c_binding/libses.c
- daemon/lsm_daemon.c
- tools/udev/scan-scsi-target.c
In the function delete_socket we check to see if the file in question
is a socket before we delete it.  Thus there is a race condition
between the checks.  Open the directory that contains the file and
use the functions that use the directory file descriptor to remove
this race condition.
CI REDO
> coverity: Correct TOCTOU

- c_binding/libsg.c
When compiling with `-fanalyzer` compiler option, the compiler was
warning that the memory pointed to by dp was leaked.  The following
change is a simplification and adds more defensive programming by
ensuring dp is not dangling after the memory that it pointed to
is assigned to the array.  The warning in this case was incorrect,
but the changes do simplify and improve.
> Fix Memleak warning

- c_binding/lsm_local_disk.c
Newer versions of gcc apparently don't like string lengths that
are determined at runtime and will emit a warning when they occur.
lsm_local_disk.c:1102:41: error: '%s' directive writing up to 2147483641
bytes into a region of size 2147483636 [-Werror=format-overflow=]
1102 |     sprintf(sysfs_sas_path, "/sys/block/%s/device/sas_address", blk_name);
A discussion:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104746
In our case we know that the string length will safely be smaller than
PATH_MAX, so we are simply replacing an unknown at compile time with
a known, so that we don't encounter this warning.
At the moment I'm not sure why this is only raised on i386.
> Correct failure to build on i386

- tools/udev/90-scsi-ua.rules
The Linux kernel has support for this event and will emit an event if a target returns this unit attention.
Add it commented out to match the others in the file.
> Add a udev rule entry for ALUA state changes

- .packit.yaml
- plugin/arcconf_plugin/arcconf.py
- plugin/arcconf_plugin/utils.py
- plugin/hpsa_plugin/hpsa.py
- plugin/hpsa_plugin/utils.py
- plugin/local_plugin/local.py
- plugin/megaraid_plugin/megaraid.py
- plugin/megaraid_plugin/utils.py
- plugin/sim_plugin/simarray.py
- plugin/sim_plugin/simulator.py
- plugin/smispy_plugin/utils.py
- plugin/targetd_plugin/targetd.py
- python_binding/lsm/_common.py
- python_binding/lsm/_data.py
- python_binding/lsm/_iplugin.py
- python_binding/lsm/_local_disk.py
- python_binding/lsm/_pluginrunner.py
- python_binding/lsm/_transport.py
- test/plugin_test.py.in
- tools/basic_check/local_check.py.in
- tools/lsmcli/cmdline.py
- tools/lsmcli/data_display.py
Hopefully this will resolve: https://github.com/libstorage/libstoragemgmt/issues/520
> Potential Megaraid fix

- plugin/nfs_plugin/nfs.py
- python_binding/lsm/_common.py
When running on a fips enabled system we encounter the following error:
```
PLUGIN_BUG(2): [digital envelope routines] unsupported Data: Traceback (most recent call last): ...
File "/usr/lib64/python3.9/site-packages/lsm/_common.py", line 348, in md5
h = hashlib.md5()
ValueError: [digital envelope routines] unsupported
```
Utilize the `usedforsecurity=False`parameter to md5 to indicate that our use is not for security related purposes.
> Correction for fips error

- .circleci/config.yml
- packaging/libstoragemgmt.spec.in
- rh_py3_rpm_dependency
- test/docker_ci_test.sh
- test/runtests.sh.in
When we added FFI to `libstoragemgm-rust` we broke our verification test when building & testing in a container.  We also stumbled upon an issue where we don't have `pkconfig-devel` which we should investigate into more as I believe there is a simpler solution that simplying adding `pkconfig-devel` to spec file.
> Add needed cargo paths for testing
